# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:18-alpine AS builder

# Create and change to the app directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the app directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code to the app directory
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Use a smaller Node.js image for the production environment
FROM node:18-alpine

# Create and change to the app directory
WORKDIR /app

# Copy the build output and package.json to the app directory
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install production dependencies only
RUN npm ci --omit=dev

# Set the environment variable for the Luma API key
ENV LUMA_API_KEY=your_api_key_here

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "build/index.js"]
